# -*- coding: utf-8 -*-
"""Atm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GrWUd-OYYLi_cXIlDet0QOd_CxAIrmv5
"""

Username = "Jagadeesh"
Password = "jagadeesh@123"
print("!_____ATM_____!")
print("=====WELCOME=====")
Customer_name = str(input("Enter your username: "))
Customer_password = str(input("Enter your password: "))

if Customer_name==Username and Customer_password==Password:
  print("=====SUCCESSFULLY LOGGED IN=====")
  print("Your Username:",Username)
  print(" ",end="\n")
  amount = 100000
  print(''' 
  1. Deposit amount
  2. Withdrawal amount
  3. Balance Enquiry
  4. Mini Statment
  5. exit
  ''')
  option = int(input("Select Your Option:"))         
                         

  if option==1:
    print("_____DEPOSIT_____")
    Deposit_amount = int(input("Enter a amount to despoit:"))
    amount+=Deposit_amount
    print("Deposited amount:",Deposit_amount)
    print("Total Balance:",amount)
    print("=====THANK YOU=====")
  elif option==2:
    print("_____Withdrawal_____")
    Withdrawal_amount = int(input("Enter a amount to withdrawal:"))
    if Withdrawal_amount>amount:
      print("Insufficient Balance",amount)
      print("Retry...")

    else:
      amount-=Withdrawal_amount
      print("Withdrawal amount:",Withdrawal_amount)
      print("Total Balance:",amount)
      print("=====THANK YOU=====")

  elif option==3:
    print("_____Balance Enquiry_____")
    print("Total Balance:",amount)
    print("=====THANK YOU=====")
  elif option==4:
    print("_____Mini Statment_____")
    print("Your Username:",Username)
    Last_Deposit = Deposit_amount
    Last_Withdrawal = Withdrawal_amount
    print("deposited:",Last_Deposit)
    print("Withdrawal:",Last_Withdrawal)
    print("Total Balance:",amount)
    print("=====THANK YOU=====")
  elif option==5:
    print("=====THANK YOU=====")
    exit()

else:
  print("Your Username or Password is Wrong")
  print("Please Enter a valid Username and Password")